config/routes.rb
Rails.application.routes.draw do

  get 'about', to: "pages#about"
  get 'contact', to: "pages#contact"
  get 'careers', to: "pages#careers"
  get 'services', to: "pages#services"
  get 'terms', to: "pages#terms"
  get 'newsletter', to: "pages#newsletter"
  get 'admin', to: "pages#admin" 

  devise_for :sellers, :path_names => { :sign_up => 'thenorthremembers' }, 
                                     controllers: {registrations: 'registrations'}
 
 
  devise_for :users, controllers: { registrations: 'registrations' }

  resources :sellers, only: [:show]

  resources :sellers do
    put :follow, on: :member
  end

  resources :sellers do
    put :unfollow, on: :member
  end

  resources :users, only: [:show]

  get 'show_follow' => 'users#show_follow', path: 'users/:id/show_follow'

  root 'listings#index'
  
  resources :listings, only: [:show, :new, :edit]

  resources :listings do
    put :save, on: :member
  end

  resources :listings do
    put :remove, on: :member
  end

  get 'listings/:id/remove_image2', to: 'listings#remove_image2', as: 'remove_listing_image2'

  
  get 'men' => 'subcategories#men', path: 'subcategories/:id/men'
  get 'women' => 'subcategories#women', path: 'subcategories/:id/women'
  get 'both' => 'subcategories#both', path: 'subcategories/:id/both'

  resources :applicants, only: [:new, :create]
  get 'rainsofcastamere', to: 'applicants#index'
  get 'thankyou', to: 'pages#thankyou'

  resources :categories, :path_names => { :edit => 'backtothefuture', :index => 'collections' }, except: [:destroy] 
  resources :subcategories, :path_names => { :edit => 'thebreakfastclub' }, except: [:destroy]
  

end

app/models/listing.rb
class Listing < ActiveRecord::Base


  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  def slug_candidates
    [:name]
  end

  def should_generate_new_friendly_id?
    name_changed?
  end

  validates :name, presence: true, length: { maximum: 75 }
  validates :image, presence: true
  validates :site, presence: true
  
  has_and_belongs_to_many :users

  
  has_attached_file :image, styles: { medium: ["300x300>", :jpg, :quality => 70], 
                     square: ["200x200>", :jpg, :quality => 70], thumb: 
                    ["100x100>", :jpg, :quality => 70],  large:  
                    ['1000>', :jpg, :quality => 70] }

  has_attached_file :image2, styles: { medium: ["300x300>", :jpg, :quality => 70], thumb: 
                    ["100x100>", :jpg, :quality => 70],  large:  
                    ['1000>', :jpg, :quality => 70] }

  has_attached_file :image3, styles: { medium: ["300x300>", :jpg, :quality => 70], thumb: 
                    ["100x100>", :jpg, :quality => 70],  large:  
                    ['1000>', :jpg, :quality => 70] }
  
  has_attached_file :image4, styles: { medium: ["300x300>", :jpg, :quality => 70], thumb: 
                    ["100x100>", :jpg, :quality => 70],  large:  
                    ['1000>', :jpg, :quality => 70] }     
  
  has_attached_file :image5, styles: { medium: ["300x300>", :jpg, :quality => 70], thumb: 
                    ["100x100>", :jpg, :quality => 70],  large:  
                    ['1000>', :jpg, :quality => 70] }

  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_attachment_content_type :image2, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_attachment_content_type :image3, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_attachment_content_type :image4, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_attachment_content_type :image5, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  
  belongs_to :category
  belongs_to :subcategory
  belongs_to :seller


def self.search(search)
  if search
    search_length = search.split.length
    #where([(['name LIKE ?'] * search_length).join(' AND ')] + search.split.map { |name| "%#{name}%" }) 
    where([(['tag ILIKE ?'] * search_length).join(' AND ')] + search.split.map { |tag| "%#{tag}%" })
  else
    find(:all)
  end 
end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
    
before_action :set_listing, only: [:show, :edit, :update, :destroy]
before_action :authenticate_seller!, except: [:index, :show, :landing, :save, :remove]
before_action :authenticate_user!, only: [:save, :remove]
before_action :require_sameseller, only: [:edit, :update, :destroy]


  def landing
    @listings = Listing.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 16)
  end

  def index
   @listings = Listing.all.order("updated_at DESC").paginate(:page => params[:page], :per_page => 16)
   if params[:search]
      @listings = Listing.search(params[:search]).order("updated_at DESC").paginate(:page => params[:page], :per_page => 16)
    else
      @listings = Listing.all.order("updated_at DESC").paginate(:page => params[:page], :per_page => 16)
    end
  end

  def new
    @listing = current_seller.listings.build
  end

    def create
      @listing = current_seller.listings.build(listing_params)
      if @listing.save
        redirect_to listing_path(@listing)
      else
        render 'new'
      end
    end

    def edit
    end

    def update
        if @listing.update(listing_params)
        redirect_to listing_path(@listing)
      else
        render 'edit'
      end
    end

    def show
      @user = current_user
      #@listing_user = current_user.listings(@listing)
      @listing_seller = @listing.seller
      set_meta_tags title: "#{@listing.name}",
                    keywords: "#{@listing.tag}",
                    description: "#{@listing.description}",
                    image_src: "#{@listing.image.url(:medium)}"
    end

    def destroy
        @listing.destroy
        redirect_to root_path
    end

    def save
        @listing = Listing.friendly.find(params[:id])
        current_user.listings << @listing
        redirect_to :back, flash: { success: 'Tee has been added to your catalogue'} 
    end

    def remove 
      @listing = Listing.friendly.find(params[:id])
      current_user.listings.delete(@listing)
      redirect_to :back, flash: { success: 'Tee has been removed from your catalogue'} 
    end

    def remove_image2
      @listing = Listing.friendly.find(params[:id])
      @listing.image2.destroy
      @listing.save
      redirect_to edit_listing_path, flash: { success: 'Image has been removed' }
    end

    private
    def listing_params
       params.require(:listing).permit(:name, :feature1, :feature2, :feature3, :feature4, :feature5, 
                                       :price, :cod, :time, :description, :image, 
                                       :image2, :image3, :image4, :image5, :site, :category_id, 
                                       :subcategory_id, :gender, :tag, :keywords, :permalink )
    end

    def set_listing
        @listing = Listing.friendly.find(params[:id])
    end

    def require_sameseller
      if current_seller != @listing.seller && !current_seller.admin 
        redirect_to root_path 
      end
    end
end

app/views/listings/_listing.html.erb
<div itemprop="product" itemscope itemtype="http://schema.org/Product">
  <div class = "container-fluid">
    <div class = "row" id="grid">
      <% obj.each do |listing| %>
          <div class = "col-xs-6 col-md-3" id="listing-box">
            <div class = "thumbnail"style="padding:6px">
              <% if listing.users && listing.users.count > 0 %>
                <% if listing.users.count == 1 %>
                  <div class="saves">
                    <div class = "save-count"><%= listing.users.count %> Save</div>
                  </div>
                <% elsif listing.users.count > 1 %>
                  <div class="saves">
                    <div class = "save-count"><%= listing.users.count %> Saves</div>
                  </div>
                <% end %>
              <% end %>
              <span itemprop="image"><%= link_to image_tag(listing.image.url(:medium)), listing %></span>
              <% if user_signed_in? %>
                <div style="float:right">
                  <% if listing.users.include?(current_user) %>
                    <div class = "save-heart-icon"><%= link_to image_tag('heart-r.png'), remove_listing_path(listing), method: :put %></div>
                  <% else %>
                    <div class = "save-heart-icon"><%= link_to image_tag('heart-b:w.png'), save_listing_path(listing), method: :put %></div>
                  <% end %>
                </div>
              <% elsif !user_signed_in? %>
                <div class = "save-heart-icon" style="float:right; margin-right: 5px"><%= link_to image_tag('heart-b:w.png'), new_user_registration_path %></div>
              <% end %>
                </div>
                  <div class="jumbotron"style="background-color:#fff;border:1px solid #DDDDDD;padding:0px;margin-top:-21px">
                    <div class = "listing_name">
                  <span itemprop="name"><%= truncate(listing.name, length: 100) %></span>
              </div>
              <div class="seller-listing">
                by<br />
                  <small><%= link_to listing.seller.name,listing.seller if listing.seller%></smaill>
              </div><br>
                  <div class="homepage-listing-engagement">
                    <%= link_to 'Buy It', listing.site, target: '_blank',:onclick => "onClick()", class: "btn-homepage" %>
                    <%= link_to 'Details', listing, class: "btn-homepage" %>
                  </div><br>
            </div>
        </div>
      <% end %>
  </div>
  </div>
   <div class="center" style="text-align:center">
      <%= will_paginate obj, renderer: BootstrapPagination::Rails %>
  </div>
</div>

app/views/listings/_listing2.html.erb
<div itemprop="product" itemscope itemtype="http://schema.org/Product">
  <div class = "container-fluid">
    <div class = "row" id="grid">
      <% obj.each do |listing| %>
          <div class = "col-xs-6 col-md-3" id="listing-box">
            <div class = "thumbnail"style="padding:6px">
              <% if listing.users && listing.users.count > 0 %>
                <% if listing.users.count == 1 %>
                  <div class="saves">
                    <div class = "save-count"><%= listing.users.count %> Save</div>
                  </div>
                <% elsif listing.users.count > 1 %>
                  <div class="saves">
                    <div class = "save-count"><%= listing.users.count %> Saves</div>
                  </div>
                <% end %>
              <% end %>
              <span itemprop="image"><%= link_to image_tag(listing.image.url(:medium)), listing %></span>
                <div style="float:right">
                  <% if listing.users.include?(current_user) %>
                  <div class = "save-heart-icon"><%= link_to image_tag('heart-r.png'), remove_listing_path(listing), method: :put %></div>
                  <% end %>
                </div>
              </div>
                  <div class="jumbotron"style="background-color:#fff;border:1px solid #DDDDDD;padding:0px;margin-top:-21px">
                    <div class = "listing_name">
                  <span itemprop="name"><%= truncate(listing.name, length: 100) %></span>
              </div>
              <div class="seller-listing">
                by<br />
                  <small><%= link_to listing.seller.name,listing.seller if listing.seller%></smaill>
              </div><br>
                <div class="homepage-listing-engagement">
                  <%= link_to 'Buy It', listing.site, target: '_blank',:onclick => "onClick()", class: "btn-homepage" %>
                  <%= link_to 'Details', listing, class: "btn-homepage" %>
              </div><br>
            </div>
        </div>
      <% end %>
  </div>
  </div>
</div>

app/views/listings/_sellerlisting.html.erb
<div itemscope itempro="organization" itemtype="http://schema.org/Organization">
  <div class = "container-fluid">
    <div class = "row" id="grid">
      <% obj.each do |x| %>
          <div class = "col-xs-6 col-md-3" id="listing-box">
            <div class = "thumbnail"style="padding:6px">
              <span itemprop="image"><%= link_to image_tag(x.avatar.url(:medium)), x %></span>
            </div>
            <div class="jumbotron"style="background-color:#fff;border:1px solid #DDDDDD;padding:0px;margin-top:-21px">
              <div class = "listing_name">
                <span itemprop="name"><%= link_to (truncate(x.name, length: 100)) %></span>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/listings/edit.html.erb
<% noindex %>
<% nofollow %>
<div class = "container">
	<h1 style="text-align:center">UPDATE T-SHIRT DETAILS</h1>
		<div class='jumbotron'>
			<%= render 'shared/errors', obj: @listing %>
				<%= form_for @listing do |l| %>
					<div class = "row">
						<div class = "col-md-6 col-xs-12">

						<%= l.label :name, 'Name (Maximum 75 Characters)' %><br />
						<%= l.text_field :name, placeholder: 'Use simple terms...', class: "form-control" %><br />
						
						<%= l.label :category %><br />
  						<%= l.collection_select :category_id, Category.order(:name),:id,:name, include_blank: true %><br /><br />

						<%= l.label :tag, 'Keywords (please use a space after each word)' %>
						<%= l.text_field :tag, placeholder: 'game of thrones tyrion drogon.....', class: "form-control" %><br/>
						
						<%= l.label :site, 'Link to tee' %><br />
						<%= l.text_field :site, placeholder: 'where can you buy it....', class: "form-control" %><br />
						
						<%= l.label :description, 'Detailed Description (Maximum 500 characters)' %>
						<%= l.text_area :description, placeholder: 'This will make your tee stand out on search engines. Create a unique and effective description.....', class: "form-control" %><br />

  						<%= l.label :image %>
						<%= l.file_field :image, class: "form-control"%><br />
						
						<%= l.submit 'UPDATE', class: 'btn btn-default btn-lg'  %>
						<%= link_to 'CANCEL', listing_path, class: 'btn btn-default btn-lg' %><br />
						</div>
					</div><br />
		</div>
						
					<% end %>
</div><br />

app/views/listings/index.html.erb
<head itemscope itemtype="http://schema.org/WebSite">
  <script>
    function onClick() {
          fbq('track');
              }
  </script>
</head>
<title itemprop='name'>Where's My Tee?</title>
<link rel="canonical" href="www.wheresmytee.com/" itemprop="url">
<span itemscope itemtype="http://schema.org/Organization">
  <link itemprop="url" href="http://www.wheresmytee.com">
  <a itemprop="sameAs" href="http://www.facebook.com/wheresmyteeapp">FB</a>
  <a itemprop="sameAs" href="http://www.instagram.com/wheresmytee">Twitter</a>
</span>
<div itemscope itemtype="http://schema.org/Product">
<% set_meta_tags title: 'We are a t-shirt search platform based in India',
                 description: 'We are an online curator of graphic t-shirts for men from a multitude of innovative brands in India. Our vast database makes online shopping extremely fast and simple.',
                 keywords: 'T-Shirts, India, Men, Graphic Tees',
                 canonical: "www.wheresmytee.com",
                 next: "http://www.wheresmytee.com/?page=2" %>
<div class="jumbo" style="height: 300px; margin-top: -41px">
    <iframe style="margin-top:10px; margin-left: 10px" src="https://www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2Fwheresmyteeapp%2F&width=141&layout=button_count&action=like&size=large&show_faces=true&share=true&height=46&appId" width="141" height="46" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
     <h1 style="text-align:center; color: #000; font-family: 'Lato-Heavy', sans-serif; margin-top: 5px">T-Shirts for the Millennial Generation</h1><br>
      <div class="main-navigation">
        <%= link_to 'Collections', categories_path, class: "btn-landing" %>
        <%= link_to 'Brands', sellers_path, class: "btn-landing" %>
      </div>
</div>
<div class = "container-fluid">
  <h2 class="product-list-header">NEW PRODUCTS</h2>
    <div class = "row" id="grid">
      <% @listings.each do |listing| %>
        <div class = "col-xs-6 col-md-3" id="listing-box">
          <div class = "thumbnail"style="padding:6px">
            <% if listing.users && listing.users.count > 0 %>
              <% if listing.users.count == 1 %>
                <div class="saves">
                  <div class = "save-count"><%= listing.users.count %> Save </div>
                </div>
              <% elsif listing.users.count > 1 %>
                <div class="saves">
                  <div class = "save-count"><%= listing.users.count %> Saves</div>
                </div>
              <% end %>
            <% end %>
           <%= link_to image_tag(listing.image.url(:medium)), listing %>
            <% if user_signed_in? %>
              <div style="float:right">
                <% if listing.users.include?(current_user) %>
                  <div class = "save-heart-icon"><%= link_to image_tag('heart-r.png'), remove_listing_path(listing), method: :put %></div>
                <% else %>
                  <div class = "save-heart-icon"><%= link_to image_tag('heart-b:w.png'), save_listing_path(listing), method: :put %></div>
                <% end %>
              </div>
            <% elsif !user_signed_in? %>
                <div class = "save-heart-icon" style="float:right; margin-right: 5px"><%= link_to image_tag('heart-b:w.png'), new_user_registration_path %></div>
            <% end %>
         </div>
          <div class="jumbotron"style="background-color:#fff;border:1px solid #DDDDDD;padding:0px;margin-top:-21px">
            <div class = "listing_name">
              <span itemprop="name">
                <%= truncate(listing.name, length: 100) %>
              </span>
            </div>
            <div class="seller-listing">
              by<br />
              <span itemprop="manufacturer">
                <small>
                  <%= link_to listing.seller.name,listing.seller if listing.seller%>
                </small><br>
              </span>
            </div><br>
              <div class="homepage-listing-engagement">
                <%= link_to 'Buy It', listing.site, target: '_blank',:onclick => "onClick()", class: "btn-homepage" %>
                <%= link_to 'Details', listing, class: "btn-homepage" %>
              </div><br>
          </div>
        </div>
      <% end %>
    </div>
</div>
<div class="center" style="text-align:center">
  <%= will_paginate @listings, renderer: BootstrapPagination::Rails %>
</div>
</div>
 

app/views/listings/landing.html.erb
<% noindex %>
<% nofollow %>
    <div class="modal fade" tabindex="-1" role="dialog" id="myModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                      <div class="modal-title"style="text-align:center; color:#fff"><%= image_tag('Logo-2.png') %></div>
                          <p class ="modal-description"style="text-align:center; color:#fff; margin-top: 20px">Looking for that perfect Tee? Explore our platform that caters to amazing products from innovative brands.</p>
                </div>
                        <div class="explore">
                            <%= link_to 'Explore Now', listings_path  %>
                            <%= link_to ' User Login', new_user_session_path %>
                        </div>
            </div>
        </div>
    </div>

<div class = "container-fluid"style="opacity:0.2">
    <div class = "row" id="grid">
          <% @listings.each do |listing| %>
          <div class = "col-xs-6 col-md-3" id="listing-box">
            <div class = "thumbnail"style="padding:6px">
                <%= link_to image_tag(listing.image.url(:medium)), listing %>
                </div>
                  <div class="jumbotron"style="background-color:#fff;border:1px solid #DDDDDD;padding:0px;margin-top:-21px">
                    <div class = "listing_name">
                  <%= truncate(listing.name, length: 100) %>
              </div>
              <div class="seller-listing">
                by<br />
                  <small><%= link_to listing.seller.name,listing.seller if listing.seller%></smaill>
              </div>
            </div>
        </div>
      <% end %>
  </div>
  </div>
  <div class="center">
   <%= will_paginate @listings, renderer: BootstrapPagination::Rails %>
</div>

 

app/views/listings/new.html.erb
<div class = "container">
	<h1 style="text-align:center">Awwwww YEAH!!!!</h1>
		<p style='text-align:center'>Add a new Tee Bro!</p>
			<div class='jumbotron'>
				<%= render 'shared/errors', obj: @listing %>
					<%= form_for @listing do |l| %>
						<div class = "row">
							<div class = "col-md-6 col-xs-12">

								<%= l.label :name, 'Name (Maximum 75 Characters)' %><br />
								<%= l.text_field :name, placeholder: 'Keep it simple...', class: "form-control" %><br />

								<%= l.label :category %><br />
		  						<%= l.collection_select :category_id, Category.order(:name),:id,:name, include_blank: true %><br /><br />

		  						<%= l.label :tag, 'Keywords' %>
								<%= l.text_field :tag, placeholder: 'game of thrones tyrion drogon.....', class: "form-control" %><br/>
						
  							</div>		
  							<div class = "col-md-6 col-xs-12">

								<%= l.label :site, 'Link to tee' %><br />
								<%= l.text_field :site, placeholder: 'where can you buy it....', class: "form-control" %><br />
								
								<%= l.label :description, 'Description' %>
								<%= l.text_area :description, placeholder: 'Keep it simple.....', class: "form-control" %><br />

								<%= l.label :image %>
								<%= l.file_field :image, class: "form-control"%><br />
								
								<%= l.submit 'CREATE', class: 'btn btn-default btn-lg'  %>
									<% if user_signed_in? %>
										<%= link_to 'CANCEL', user_path(current_user), class: 'btn btn-default btn-lg' %><br />
									<% elsif seller_signed_in? %>
										<%= link_to 'CANCEL', seller_path(current_seller), class: 'btn btn-default btn-lg' %><br />
									<% end %>
							</div>
						</div><br />
					<% end %>
			</div>
</div><br />

app/views/listings/show.html.erb
<html>
<head>
	<script>
		function onClick() {
  				fbq('track');
							}
	</script>
	<% content_for :head do %>
  		<meta property="og:image" content= "<%= @listing.image.url(:medium) %>" />
		<meta property="og:description" content= "We are a T-Shirt search engine" />
  		<meta property="og:title" content= "<%= @listing.name %>" />
  		<meta name="twitter:card" content= "summary" />
	<% end %>
</head>
<body>
<div class="jumbo" style="height: 300px; margin-top: -21px">
    <iframe style="margin-top:10px; margin-left: 10px" src="https://www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2Fwheresmyteeapp%2F&width=141&layout=button_count&action=like&size=large&show_faces=true&share=true&height=46&appId" width="141" height="46" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
     <h1 style="text-align:center; color: #000; font-family: 'Lato-Heavy', sans-serif; margin-top: 5px">T-Shirts for the Millennial Generation</h1><br>
      <div class="main-navigation">
        <%= link_to 'Collections', categories_path, class: "btn-landing" %>
        <%= link_to 'Brands', sellers_path, class: "btn-landing" %>
      </div>
</div><br />
<div itemprop="product" itemscope itemtype="http://schema.org/Product">
	<div class = "container">
		<div class = "jumbotron"style="background-color:#fff;border-radius:5px;border:3px solid #000">
			<%= link_to 'Back', categories_path, class: "btn btn-default" %><br /><br />	
			<div class = "row">
				<div class = "col-md-6">
					<%= image_tag @listing.image.url(:medium), :data => { zoom_image: @listing.image.url(:large) }, :class => "zoom" %> <br /><br /><br />
					<div class ="row">
						<div class = "col-md-12 col-xs-12">
							<div id="gallery">
								<%= link_to image_tag(@listing.image.url(:thumb)), '#', data: { image: @listing.image.url(:medium), zoom_image: @listing.image.url(:large) }, :class => 'zoom2' %>
							</div>
						</div>
					</div>		
				</div>		
					<div class = "col-md-6">
						<div class = "listing_set_1">
							<div class="title">
									Name: <br/>
							</div>
							<div class="fill">
								<span itemprop="name">
									<%= @listing.name %>
								</span>		
							</div>
							<div class="by"style="font-weight:bold">by</div>
						</div>
						<div class="seller-name-on-product">
							<span itemprop="manufacturer"><%= link_to @listing.seller.name, @listing.seller if @listing.seller %></span>
						</div>
						<div class="know-more"><%= link_to '(Know more about this brand)', @listing.seller %></div><br>
							<div class="social-share">
								<%= social_share_button_tag(@listing.name, :image => @listing.image.url(:medium), 'data-twitter-title' => "#wheresmytee #{@listing.name} ", 'data-facebook-title' => "Get your #{@listing.name} tee from Where's My Tee?", 'data-pinterest-title' => "Get your #{@listing.name} tee from Where's My Tee?") %>
							</div>
							<% if @listing.description? %>
								<h4 style="font-family: 'Lato-Medium', sans-serif; font-size: 20px; font-weight: bold">Description:</h4>
							<% end %>
							<div class="des" style="font-family:'Lato-Light', sans-serif'"> 
								<span itemprop="description"><%= @listing.description %></span><br><br>
							</div>
							<div class="save-buy" style="display:flex">
								<% if user_signed_in? %>
									<% if @listing.users.include?(current_user) %>
										<div class="save-remove"><%= link_to 'Unsave', remove_listing_path(@listing), method: :put %></div>
									<% else %>
										<div class="save-remove"><%= link_to 'Save', save_listing_path(@listing), method: :put %></div>
									<% end %><br /><br />
								<% elsif (current_seller == @listing.seller) || (seller_signed_in? && current_seller.admin) %>
									<div class="edit-delete" style="float:right"><%= link_to 'Edit', edit_listing_path(@listing), class: "btn btn-success" %>
										<%= link_to 'Delete', listing_path(@listing), method: :delete, data: { confirm: "Are you sure you want to delete this listing"},class: "btn btn-success" %> 
									</div>
								<% elsif !seller_signed_in? && !user_signed_in? %>
									<div class="save-remove"><%= link_to 'Save', new_user_registration_path %></div>
								<% end %><br><br>
										<%= link_to 'More Info', "#{@listing.site}", :target => "_blank", 
													:onclick => "onClick()",
													class: 'btn-buy-it-now' %>
							</div><br> 

					  </div>	
			</div>
		</div>
	</div>
    <div>
    	<h4 class="seperator">similar products</h4>
    </div>
      		
<div class = "container-fluid">
	<div class = "row" id="grid">
		<% Listing.all.where(:category => @listing.category).each do |listing| %>
			<div class = "col-xs-6 col-md-3" id="listing-box">
		    	<div class = "thumbnail"style="padding:6px">
		    		<% if listing.users && listing.users.count > 0 %>
              			<% if listing.users.count == 1 %>
                			<div class="saves">
                  				<div class = "save-count"><%= listing.users.count %> Save</div>
                			</div>
              			<% elsif listing.users.count > 1 %>
                			<div class="saves">
                  				<div class = "save-count"><%= listing.users.count %> Saves</div>
                			</div>
              			<% end %>
            		<% end %>
             		<%= link_to image_tag(listing.image.url(:medium)), listing %>
             	</div>
             	<div class="jumbotron"style="background-color:#fff;border:1px solid #DDDDDD;padding:0px;margin-top:-21px">
             		<div class = "listing_name">
			   			<%= truncate(listing.name, length: 100) %>
			 		</div>
			 		<div class="seller-listing">
			 					by<br />
			 			<small><span itemprop="manufacturer"><%= link_to listing.seller.name,listing.seller if listing.seller %></span></smaill>
			 		</div><br>
			 		<div class="homepage-listing-engagement">
                		<%= link_to 'Buy It', listing.site, target: '_blank',:onclick => "onClick()", class: "btn-homepage" %>
                		<%= link_to 'Details', listing, class: "btn-homepage" %>
              		</div><br>
			 	</div>
			 </div>
		<% end %>
</div>
</div>
</body>
</html>
		

		