config/routes.rb
Rails.application.routes.draw do

  get 'about', to: "pages#about"
  get 'contact', to: "pages#contact"
  get 'careers', to: "pages#careers"
  get 'services', to: "pages#services"
  get 'terms', to: "pages#terms"
  get 'newsletter', to: "pages#newsletter"
  get 'admin', to: "pages#admin" 

  devise_for :sellers, :path_names => { :sign_up => 'thenorthremembers' }, 
                                     controllers: {registrations: 'registrations'}
 
 
  devise_for :users, controllers: { registrations: 'registrations' }

  resources :sellers, only: [:show]

  resources :sellers do
    put :follow, on: :member
  end

  resources :sellers do
    put :unfollow, on: :member
  end

  resources :users, only: [:show]

  get 'show_follow' => 'users#show_follow', path: 'users/:id/show_follow'

  root 'listings#index'
  
  resources :listings, only: [:show, :new, :edit]

  resources :listings do
    put :save, on: :member
  end

  resources :listings do
    put :remove, on: :member
  end

  get 'listings/:id/remove_image2', to: 'listings#remove_image2', as: 'remove_listing_image2'

  
  get 'men' => 'subcategories#men', path: 'subcategories/:id/men'
  get 'women' => 'subcategories#women', path: 'subcategories/:id/women'
  get 'both' => 'subcategories#both', path: 'subcategories/:id/both'

  resources :applicants, only: [:new, :create]
  get 'rainsofcastamere', to: 'applicants#index'
  get 'thankyou', to: 'pages#thankyou'

  resources :categories, :path_names => { :edit => 'backtothefuture', :index => 'collections' }, except: [:destroy] 
  resources :subcategories, :path_names => { :edit => 'thebreakfastclub' }, except: [:destroy]
  

end

app/models/seller.rb
class Seller < ActiveRecord::Base
 
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 
  has_many :listings
 
  validates :name, presence: true
 
  validates :name, uniqueness: true
  
  has_and_belongs_to_many :users

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
  
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController

before_action :authenticate_user!, only: [:follow, :unfollow]

#before_filter :authenticate_seller!

  def index
    @sellers = Seller.all 
  end

  def show
    @seller = Seller.friendly.find(params[:id])
    @seller_listings = @seller.listings.order("updated_at DESC").paginate(:page => params[:page], :per_page => 16)
    set_meta_tags title: "#{@seller.name}",
                  keywords: "#{@seller.keywords}",
                  description: "#{@seller.description}",
                  image_src: "#{@seller.avatar.url(:medium)}"
  end

  def follow
     @seller = Seller.friendly.find(params[:id])
     current_user.sellers << @seller
     redirect_to seller_path(@seller)
  end

  def unfollow 
      @seller = Seller.friendly.find(params[:id])
      current_user.sellers.delete(@seller)
      redirect_to seller_path(@seller)
  end
end

app/views/sellers/index.html.erb
<div itemscope itempro="organization" itemtype="http://schema.org/Organization">
<div class="jumbo" style="height: 300px; margin-top: -21px">
    <iframe style="margin-top:10px; margin-left: 10px" src="https://www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2Fwheresmyteeapp%2F&width=141&layout=button_count&action=like&size=large&show_faces=true&share=true&height=46&appId" width="141" height="46" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
     <h1 style="text-align:center; color: #000; font-family: 'Lato-Heavy', sans-serif; margin-top: 5px">T-Shirts for the Millennial Generation</h1><br>
      <div class="main-navigation">
        <%= link_to 'Collections', categories_path, class: "btn-landing" %>
        <%= link_to 'Brands', sellers_path, class: "btn-landing" %>
      </div>
</div><br />
  <div class = "container">
    <h2  class="product-list-header">FEATURED BRANDS</h2><br>
      <div class = "c-row" id="c-grid">
        <% @sellers.where(:admin => false).each do |s| %>
          <% if s.listings.count > 0 %>
            <div class = "col-xs-6 col-md-3" id="category-box">
              <div class = "image_c"style="padding:6px">
                <span itemprop="image"><%= link_to image_tag(s.avatar.url(:medium) ), s %></span>
                  <div class="overlay">
                  </div>
                  <span class="text"><span itemprop="name"><%= link_to s.name, s %></span></span>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
  </div>
</div>

app/views/sellers/show.html.erb
<head>
	<script>
		function onClick() {
  				fbq('track');
  			}
							
	</script>
</head>
<div itemscope itempro="organization" itemtype="http://schema.org/Organization">
<div class="jumbo" style="height: 300px; margin-top: -21px">
    <iframe style="margin-top:10px; margin-left: 10px" src="https://www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2Fwheresmyteeapp%2F&width=141&layout=button_count&action=like&size=large&show_faces=true&share=true&height=46&appId" width="141" height="46" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
     <h1 style="text-align:center; color: #000; font-family: 'Lato-Heavy', sans-serif; margin-top: 5px">T-Shirts for the Millennial Generation</h1><br>
      <div class="main-navigation">
        <%= link_to 'Collections', categories_path, class: "btn-landing" %>
        <%= link_to 'Brands', sellers_path, class: "btn-landing" %>
      </div>
</div><br />
	<div class="container-fluid">
		<div class="jumbotron" style="border:1px solid grey;border-radius: 3px;background-color:#fff">
			<div class="row">
				<div class="col-md-3">
					<span itemprop="image"><%= image_tag(@seller.avatar(:medium), class: 'img-circle') if @seller.avatar? %></span>
				</div>
				<div class="col-md-6">
					<div class="seller-name">
						<span itemprop="name">
							<h1><%= @seller.name %></h1>
						</span>
					</div>
					<div class="seller-description">
						<span itemprop="description">
							<p><%= @seller.description %></p>
						</span>
					</div>
					<div class="seller-location">
						<span itemprop="foundingLocation">
							<p><%= @seller.location %></p>
						</span>
					</div>
					<div class="f-u">
						<% if user_signed_in? %>
							<% if @seller.users.include?(current_user) %>
								<div class="follow-unfollow"><%= link_to 'Unfollow', unfollow_seller_path(@seller), method: :put %>
								</div>
							<% else %>
								<div class="follow-unfollow"><%= link_to 'Follow', follow_seller_path(@seller), method: :put %>
								</div>	
							<% end %>
						<% elsif !seller_signed_in? && !user_signed_in? %>
							<div class="follow-unfollow"><%= link_to 'Follow', new_user_registration_path %></div>
						<% end %>
					</div><br />	
					<% if @seller.users.count == 1 %>
						<div class="user-count">
							<%= @seller.users.count %>
								<p>Follower</p>
						</div>
					<% elsif @seller.users.count > 1 || @seller.users.count < 1 %>							
						<div class="user-count">
							<%= @seller.users.count %>				
							<p>Followers</p>
						</div>
					<% end %>
				</div>
			</div><br />
			<div class="icons">
				<%= link_to image_tag('pinterest.png'), @seller.social4, :target => "_blank"   if @seller.social4? %>
				<%= link_to image_tag('instagram.png'), @seller.social3, :target => "_blank"   if @seller.social3? %>
				<%= link_to image_tag('twitter.png'), @seller.social2, :target => "_blank"  if @seller.social2? %>
				<%= link_to image_tag('facebook.png'), @seller.social1, :target => "_blank" if @seller.social1%>
			</div>
		</div>
	</div>
	<h2  class="product-list-header">KEY PRODUCTS</h2>
	<% if current_seller == @seller %>
		<%= link_to 'Add a new product', new_listing_path, class: "btn btn-default" %><br /><br />
	<% end %>
</div>
<%= render 'listings/listing', obj: @seller_listings %>

 			