config/routes.rb
Rails.application.routes.draw do

  get 'about', to: "pages#about"
  get 'contact', to: "pages#contact"
  get 'careers', to: "pages#careers"
  get 'services', to: "pages#services"
  get 'terms', to: "pages#terms"
  get 'newsletter', to: "pages#newsletter"
  get 'admin', to: "pages#admin" 

  devise_for :sellers, :path_names => { :sign_up => 'thenorthremembers' }, 
                                     controllers: {registrations: 'registrations'}
 
 
  devise_for :users, controllers: { registrations: 'registrations' }

  resources :sellers, only: [:show]

  resources :sellers do
    put :follow, on: :member
  end

  resources :sellers do
    put :unfollow, on: :member
  end

  resources :users, only: [:show]

  get 'show_follow' => 'users#show_follow', path: 'users/:id/show_follow'

  root 'listings#index'
  
  resources :listings, only: [:show, :new, :edit]

  resources :listings do
    put :save, on: :member
  end

  resources :listings do
    put :remove, on: :member
  end

  get 'listings/:id/remove_image2', to: 'listings#remove_image2', as: 'remove_listing_image2'

  
  get 'men' => 'subcategories#men', path: 'subcategories/:id/men'
  get 'women' => 'subcategories#women', path: 'subcategories/:id/women'
  get 'both' => 'subcategories#both', path: 'subcategories/:id/both'

  resources :applicants, only: [:new, :create]
  get 'rainsofcastamere', to: 'applicants#index'
  get 'thankyou', to: 'pages#thankyou'

  resources :categories, :path_names => { :edit => 'backtothefuture', :index => 'collections' }, except: [:destroy] 
  resources :subcategories, :path_names => { :edit => 'thebreakfastclub' }, except: [:destroy]
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :email, presence: true
  validates :email, uniqueness: true
  validates :location, length: { maximum: 140 }
  validates :description, length: { maximum: 140 }
  extend FriendlyId
  friendly_id :name

  has_and_belongs_to_many :listings
  has_and_belongs_to_many :sellers
  
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/images/user.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

end 

app/controllers/users_controller.rb
class UsersController < ApplicationController

#before_filter :authenticat_user!

  def show
    @user = User.friendly.find(params[:id])
    @user_listings = @user.listings.order("updated_at DESC")
  end

  def show_follow
  	@user = User.friendly.find(params[:id])
  	@user_sellers = @user.sellers
  end
end

app/views/users/show.html.erb
<head>
  <script>
    function onClick() {
          fbq('track');
              }
  </script>
</head>
<div class="jumbo" style="height: 300px; margin-top: -21px">
    <iframe style="margin-top:10px; margin-left: 10px" src="https://www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2Fwheresmyteeapp%2F&width=141&layout=button_count&action=like&size=large&show_faces=true&share=true&height=46&appId" width="141" height="46" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe>
     <h1 style="text-align:center; color: #000; font-family: 'Lato-Heavy', sans-serif; margin-top: 5px">T-Shirts for the Millennial Generation</h1><br>
      <div class="main-navigation">
        <%= link_to 'Collections', categories_path, class: "btn-landing" %>
        <%= link_to 'Brands', sellers_path, class: "btn-landing" %>
      </div>
</div><br />
<div class="container-fluid">
  <div class="jumbotron" style="border:1px solid grey;border-radius: 3px;background-color:#fff">
    <div class="row">
      <div class="col-md-3">
        <% if @user.avatar? %>
          <%= image_tag(@user.avatar(:medium), class: 'img-circle') %>
        <% else %>
          <div class="user-default"><%= image_tag('user.png') %></div>
        <% end %>
      </div>
      
        <div class="col-md-6">
          <div class="user-name">
            <h1><%= @user.name %></h1>
            <p style="font-family: 'Lato-Light', sans-serif"><%= @user.location %></p>
            <p style="font-family: 'Lato-Regular', sans-serif; font-size: 15px"><%= @user.description %></p>
          </div>
        </div>
    </div><br />
</div>
</div>
<div id="user-header">
	<div class="col-xs-6 col-md-6" style="text-align:center; border: 1px solid #fff; padding-top: 10px; padding-bottom: 10px; border-radius: 5px; background-color: #000 ">
		<div class="catalogue"><%= link_to 'MY BRANDS', show_follow_path(current_user) %></div>
	</div>
		<div class="col-xs-6 col-md-6" style="text-align:center; border: 1px solid #fff; padding-top: 10px; padding-bottom: 10px; border-radius: 5px; background-color: #000">
			<div class="catalogue"><%= link_to 'MY TEES', user_path(current_user) %></div>
		</div>
</div><br /><br />
<%= render 'listings/listing2', obj: @user_listings %>

app/views/users/show_follow.html.erb
<div class="container-fluid">
  <div class="jumbotron" style="border:1px solid grey;border-radius: 3px;background-color:#fff">
    <div class="row">
      <div class="col-md-3">
        <% if @user.avatar? %>
          <%= image_tag(@user.avatar(:medium), class: 'img-circle') %>
        <% else %>
          <div class="user-default"><%= image_tag('user.png') %></div>
        <% end %>
      </div>
        <div class="col-md-6">
          <div class="user-name">
            <h1><%= @user.name %></h1>
            <p style="font-family: 'Lato-Light', sans-serif"><%= @user.location %></p>
            <p style="font-family: 'Lato-Regular', sans-serif; font-size: 15px"><%= @user.description %></p>
          </div>
        </div>
    </div><br />
</div>
</div>
<div id="user-header">
	<div class="col-xs-6 col-md-6" style="text-align:center; border: 1px solid #fff; padding-top: 10px; padding-bottom: 10px; border-radius: 5px; background-color: #000 ">
		<div class="catalogue"><%= link_to 'MY BRANDS', show_follow_path(current_user) %></div>
	</div>
		<div class="col-xs-6 col-md-6" style="text-align:center; border: 1px solid #fff; padding-top: 10px; padding-bottom: 10px; border-radius: 5px; background-color: #000">
			<div class="catalogue"><%= link_to 'MY TEES', user_path(current_user) %></div>
		</div>
</div><br /><br />
<%= render 'listings/sellerlisting', obj: @user_sellers %>