config/routes.rb
Rails.application.routes.draw do

  get 'about', to: "pages#about"
  get 'contact', to: "pages#contact"
  get 'careers', to: "pages#careers"
  get 'services', to: "pages#services"
  get 'terms', to: "pages#terms"
  get 'newsletter', to: "pages#newsletter"
  get 'admin', to: "pages#admin" 

  devise_for :sellers, :path_names => { :sign_up => 'thenorthremembers' }, 
                                     controllers: {registrations: 'registrations'}
 
 
  devise_for :users, controllers: { registrations: 'registrations' }

  resources :sellers, only: [:show]

  resources :sellers do
    put :follow, on: :member
  end

  resources :sellers do
    put :unfollow, on: :member
  end

  resources :users, only: [:show]

  get 'show_follow' => 'users#show_follow', path: 'users/:id/show_follow'

  root 'listings#index'
  
  resources :listings, only: [:show, :new, :edit]

  resources :listings do
    put :save, on: :member
  end

  resources :listings do
    put :remove, on: :member
  end

  get 'listings/:id/remove_image2', to: 'listings#remove_image2', as: 'remove_listing_image2'

  
  get 'men' => 'subcategories#men', path: 'subcategories/:id/men'
  get 'women' => 'subcategories#women', path: 'subcategories/:id/women'
  get 'both' => 'subcategories#both', path: 'subcategories/:id/both'

  resources :applicants, only: [:new, :create]
  get 'rainsofcastamere', to: 'applicants#index'
  get 'thankyou', to: 'pages#thankyou'

  resources :categories, :path_names => { :edit => 'backtothefuture', :index => 'collections' }, except: [:destroy] 
  resources :subcategories, :path_names => { :edit => 'thebreakfastclub' }, except: [:destroy]
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
      <div class="container-fluid">
      	<div class="row"style="padding:20px;background-color:#000">
      		<div class="company-details">
      			<div class="col-md-3 col-xs-12">
				  	<h4>Our Company</h4>
						<p><%= link_to 'About Us', about_path %></p>
					    <p><%= link_to 'Careers', careers_path %></p>
					    <p><%= link_to 'Newsletter', newsletter_path %></p>
					    <p><%= link_to 'Contact', contact_path %></p>
			    </div>
      			<div class="col-md-3 col-xs-12">
	  				<h4>Partner with us</h4>
						<p><%= link_to 'Become a Seller', new_applicant_path %></p>
		    			<p><%= link_to 'Already a Seller?', new_seller_session_path %></p>
	  			</div>
	  			<div class="col-md-3 col-xs-12">
	  				<h4>Security and Policy</h4>
						<p><%= link_to 'Terms and Conditions', terms_path %></p>
						<p><%= link_to 'Products and Services', services_path %></p>
   	  			</div><br /><br />
   	  			  <div class="social-icons">
              		<%= link_to image_tag('fb.png'), 'https://www.facebook.com/wheresmyteeapp/', :target => "_blank" %>
              		<%= link_to image_tag('in.png'), 'https://www.instagram.com/wheresmytee/', :target => "_blank" %>
              		<%= link_to image_tag('tweet.png'), 'https://twitter.com/wheresmytee', :target => "_blank" %>
              		<%= link_to image_tag('pin.png'), 'https://www.pinterest.com/pritishsai/', :target => "_blank" %>
   				  </div>
      		</div>
  	  	</div>
      	<!-- <div class="row"style="padding:20px;background-color:#000; margin-top: -5px">
      		<p style="color: #fff; text-align: center">Copyright © 2017 Skychaser Labs Private Limited. All rights reserved.</p>
      	</div> -->
      </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" style="background-color:#000000; width: 100.5%; margin-left: -1px">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <div class ="navbar-logo">
          <%= link_to image_tag('Logo-3.png'),listings_path %>
        </div>
    </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav col-xs-8 col-md-8" style="margin-left: 10px">
            <%= form_tag(listings_path, :method => "get") do %>
              <div class="search-form">
                <%= text_field_tag :search, params[:search], placeholder: "Start your search.......", class: "form-control search-1" %>
                <%= button_tag "", type: 'submit', class: "btn btn-default glyphicon glyphicon-search" %>
                <% if seller_signed_in? && current_seller.admin %>
                  <div style="margin-left: 10px; margin-top: 3px"><%= link_to "Admin", admin_path, class: "btn btn-danger" %></div>
                  <div style="margin-left: 10px; margin-top: 3px"><%= link_to "Applicants", rainsofcastamere_path, class: "btn btn-danger" %></div>
                <% end %>
              </div>
            <% end %>
        </ul>
        <% if seller_signed_in? %>
          <div class="dropdown"style="margin-top:8px">
            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" style="margin-top: 5px">Account
                <span class="caret"></span>
            </button>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                <li><%= link_to 'My Store',seller_path(current_seller), class: "seller-header"%></li>
                <li><%= link_to 'Account Settings', edit_seller_registration_path, class: "seller-header" %></li>
                <li><%= link_to 'Log Out', destroy_seller_session_path, method: :delete, class: "seller-header" %></li>
              </ul>
          </div>
        <% elsif user_signed_in? %>
            <div class="dropdown"style="margin-top:8px">
              <button class="btn account-btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"  style="margin-top: 5px">Account
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                <li><%= link_to 'My Profile',user_path(current_user), class: "seller-header"%></li>
                <li><%= link_to 'Account Settings', edit_user_registration_path, class: "seller-header" %></li>
                <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "seller-header" %></li>
              </ul>
            </div>
        <% else %>

                <div class="login"><%= link_to 'Login', new_user_session_path %></div>
                <div class="login"><%= link_to 'Sign Up', new_user_registration_path %></div>
      <% end %>
      </div>
  </div>
</nav>
  

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<%= display_meta_tags site: "Where's My Tee ?" %>
<%= favicon_link_tag 'tab-logo.png' %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="p:domain_verify" content="f28842e2e65b0b88b2d9a3a711cb2f8f"/>
<%= content_for?(:head) ? yield(:head) : '' %>
<!-- Facebook Pixel Code -->
<script>
  !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
  n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
  n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
  t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
  document,'script','https://connect.facebook.net/en_US/fbevents.js');
  fbq('init', '1098893413554611'); // Insert your pixel ID here.
fbq('track', 'PageView');
</script>
<noscript><img height="1" width="1" style="display:none"
src="https://www.facebook.com/tr?id=1098893413554611&ev=PageView&noscript=1"
/>
</noscript>
<!-- DO NOT MODIFY -->
<!-- End Facebook Pixel Code -->
</head>
<body>
   
 <div class="wrapper">
		<%= render 'layouts/header' %>
		<%= render 'layouts/messages' %>
    <%= yield %>
  </div>
 		<div class="push"></div>
 			<%= render 'layouts/footer' %>
</body>
</html>